print("Veuillez entrer vos 4 notes en électricité")
print("NB : UTILISER . POUR SEPARER VOS NOTES EXEMPLE 14.50")
note1 = float(input("entrez la premier note :"))
note2 = float(input("entrez la deuxième note :"))
note3 = float(input("entrez la troisième note :"))
note4 = float(input("entrez la quatrième note :"))
print("les notes des devoirs compte pour 40% ")

moyenne_devoir = round((note1+note2+note3+note4)/4,2)
print("votre moyenne pour les devoirs est :",moyenne_devoir)
print("pour valider l'EU d'électricité il faut avoir 10/20 comme moyenne général")
point_acquis = round(moyenne_devoir*0.40,2)
print("point déjà acquis est :",point_acquis,"ce qui represant",point_acquis,"/20")
moyenne_restant = round(10-point_acquis,2)
print("Il vous reste :", moyenne_restant,"pour valider")
note_examen = round(moyenne_restant/0.60,2)
print("ce qui represante pour la note d'examen :",note_examen)

print("EN CONCLUSION IL TE FAUT AVOIR:",note_examen,"pour valide l'ecue électricité")